### ISSUE TITLE
Does not work with v3.3.0

### ISSUE THREAD

**Issue by datnd299** [glizzykingdreko/akamai-sensordata-decryptor#1]
script not working with this string of mine, please help
`3,i,X4yOi5PCmDKU8F3EU75CY0UJV19p5uTy9msEUQNvaJbtP6TYC3fd7kwlWBKXIonTG5U09h5gz7IltTFYtCPizpOTt1RrhKjwWwx2vqPHMmNj5HWChA01F3WsjmOxHqc1hY00JeNB5Y/I0KHIxacFM60N5bytlzWiaeFlzi0LnFM=,CiTXGDvSnO9AUJ8D/DKmFbGQRE5mikjaMk68NFJCFLLXK1Y0vn/3XIoF8sWBtacwEEmet2WnMJxoTucnim2/bf2fs7pmIJ614OxirvEuQEvP4yhTGAM7kRIpCJZ6IN+aX3NnQ1z1xNss3Lh2cYAN/WrDOn2wBXYXP0c0osaLf40=$l+rRT2iiGW8S/EgG2+R2U4PxQ/0MQF3RCrx/at33wfOuh2Z+myImuJ1ggFo2XoysEsNCO3dWb776Pz3NqRT0wA9FrVYfEheJVgSmWzzGLURL4sSC5nI0v8YI3t3OfR+1r7aI9efp1fOb55DlH3xTcr6E0hxNqQZm31DJk3WNs+DcgfZNjM+blia5He+l5+4XUuO1ED6sIEAezsj5a0V5Mguxz8lqNv2oQBqSAjZ3GuPMfU/aQSMZL41FJLTYGLnaFs9Xxrnqz761gnZHPbRbAEYTKBVHPIChSUpaerMTNq34vaTDiw23dcP+RJl5IjzlC4Oxvajlxnvo4cjkBZzSCD/Wt6jUaSKtcq2U7L5/heow28yueTVKWXrpZyziKC8dxB9gp0ZT6wiFDFHvwlgWy2GuDE0KlyAbCzwXE26pfpSssjDL0u3ObXHLzjYNxd4/1VrDkTlaUQFQ6eQxU453MroguUpAbXMuhao1Q2jhVtP49r1Yt9uu6QbkkIeNPd67xTyQfIpvy/pJOrhsg/KxE366JbvAJtP/Z3yHY2/XVwDQJIejRpD3MYc/0xlBa2fR8O12g6MjS54HbCXoyTRNiZXnNBp20kRleMqFu5s1UL+Th6uATbRj40Sbf26IcvD/fTE52Kta8AW+HrX2DE3khQ8+nnRRvwLVm8FXFXIEThkkbPY7Rxp6b5oucxmEi2Tu2yEBoWMa/Vkx8NPNIpeHtOWWrrUJHh5E8cyKLgCWCiWwApJLAcWlgNbyX98T5CCXbCPWumDoQYsGoMrwlOHEfbn/d3XxnUecdlkAsGgGS57QdWYHDoccb+4m0cb5aaM1KOS7mVg/sey8a6baCWm8cVKF/cAaHMDy+soBszMU/U+B6LYgalEf3wNwpqFjITm5FDRC8SRCL47/7Vqx/Ft8EVNmj9Qec4ih9fa3nL7SlBZDP+w2/Kv6N6BdI+xKFnJKKMI++Zq1SP438WwVYOaq4/lUmeyz+mfR6vSWShfRUYyN/xH9Rm+i2lokP6Zwun55DTkBO02ejlhd0KuC7j7bfeWhAXETvE+/YeayqXIyRoU/04yD9w7mx9BfxV6wNWW8dyRGB2yzYtu5KACApLAcGAoyP3BL8YXN109uhepT+NG+cd+W3JLttIMZMNHO+ULnR918x4UcRekKpgMwxxSzLRHCigNfZWlxlWySAWLKdHfWHEaQCrV7knseYab4nlhi4kQzdzqc18CLHPcKSiSsyvELhdhyLcubdJLRgfAhucEiimYt2Fatz91feoNqmia0MjxbZFQ3NJe5/nr6OEQKb2B/alPPOAjMIwLclxQkECkikN0ghJZ3fi3mBdz82hP4LB/n0aFFQ8KFoGPp3blhI/67czxsgbc1qJvFAs8KLfqZ0QLXaAKg4nnTxFq83Eco34E+xysYleaBmHsFeCkzum/iXjl3NVjZhiENB+R1pGJOdValVJa9PujdMs5h54UOQRv1B5O/0Y53UR4+tbbueqxX2am6/qmB0kV723iUkNJkQua32+qKHEd13S0pp90l7YUrf1gaAG7agfZznkpBHTEn9I4+K+QFUPlxg4pev8mliW5yAg4Knd7lghym2+gspWkjYOqLgqb0/eqHu1uL1eQQ4bztthnjT9a9uFVIPtkOtjLSI6/XNYX41YEhk39c3gtPHYivs9Mfq/k8uopYidlSImPuWK9LOMxQ7NFn+8kWgcK/OUhaYNVQSxkAdXoNB+xHh0fsQDEO0BXrUBFl9gHk9dtDyi+wfbAipVm2xUGI5KUa3BHNfoUfZgtxiEkUzClxwVAq8yEydtpBRHq/snmG+YMoUKvvlpdPF2Pi61Wy/qd80kmOs1mF0VVtYfS2IfZuir5OXIs1R8ymb4ObTJn+cfh6L/WfGIYrcrDLw5Que3p6o0yezIe9Fokp/BN0Q7zt7DSex/CODasRIhnzPOfZmDAXjQtcsAwGyf32esnXFsHR6Whv0as/mL0nhbcQXjRZ3v00/E8xDEUv69bpyHtSyioD2j340gN4csbpvK5O8JZ5aMbbz7Xvz7wqs5QB3nS3p4M1AiBNY3c3RTOWHjOo6uQGQhhpYmlZ53CCXZUYZo3VgLskUY2auTNkAPWqSUtDBiBNc9iOQVrUnOqfrq2CN5c5i+TrhKpBVVLntNO1D8H7vjOtTujjEwbR4gX0/g7SDctMgy5vM6CLVfhJJXaaf7c484Cta/xIsR7DB0Tk6xOkCk4CSXuGLFzWZ8sO0xwF63aX5pheccIt5O/in2nAWSYqICEes3UA0c9AOSuLs9pYRIfxSr05bJJcgXZjKbg6iqN0tDYyFMNtHDOTAeSwxf9Uu2XvsnAik6gACVm+2Cz6jYDBezLgTAyJC0nhlePekZaOiEJMAUTnubW0Jbd5PlE0VIDwrmnzu1xmN25wVx7cf35jZibJ6NrMgs9+XW70rSB/nn5WXhtEmx/PdNfkAsf+cxUPFCc5OG/3WQ59pl99KUUxtOLCboProgwvjTrW/sIgOWsQicAtghwUQSyMDRrSKqhEuDF4n+Y25Zi6pvoeFUiudMUcQfTUOtkHAgzC6jmPnsTXLssNozrOguyF+/VI7kMOn5hTDNaFXmqf81NBqThHX5N1XaDBBUgA4NIcTStoD7a/7pLSkUfsFHruVIQwP44uywwTUTaplOGTvWU3cn2N78diJsFT4LTDEkBgMZYIUFefM6N9nJapF8hIpX+Bt6nqf+WgbbEeGIp8Lq00X62ElWhXTeIsx35EePuJNlqubdYQZXaLlwNpdZGHOd7ITD9SDE2LDLfahUZ6u4COsRyMxOf+MnJBRR2qnRGbjGe8bNJUsaqCTUZwvUj4090MzLLvS90Sc3BnyrcWQvHNQ6tx0b+JRo3DUBALqnkbUTwtQtYSlSit2anJj2t89/Y4LkMHksJLH92N7izr3M8nquejCqfhhxTGTxNW6s0RPgSzvYBV8Sjw97NE/RC6N7QhgEyUMOAvK5FTLOqLs3SERZf01WVjMyD5m2/gRmDNZfDfju/SF+VCyru0wTShw23sED837KhpSLOHi8y7mxF8N5G3eP8+OYS+xalq$12,5,21$$`

**Comment by glizzykingdreko** [comment]
Hi!
Unfortunately i’m not maintaining that repo anymore, anyway if you have specific needs feel free to join my server and open a ticket:

https://discord.gg/GMTjRJZp

Kind regards, Glizzy

**Comment by fripokoff** [comment]
Hi discord expired

**Comment by glizzykingdreko** [comment]
https://takionapi.tech/discord

26, Fripok ***@***.***(mailto:26, Fripok <<a href=)> escreveu:
